package com.example.demo.sevee.repository.modelo.to;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;
import java.util.function.Predicate;

public class Funciones {
	
	public static <T> Predicate<T> distinctPorCodigo(Function<? super T, Object> keyExtractor) 
	{
	    Map<Object, Boolean> map = new ConcurrentHashMap<>();
	    return t -> map.putIfAbsent(keyExtractor.apply(t), Boolean.TRUE) == null;
	}

	public static Integer provChange(String provincia) {
		Map<String, Integer> mapaProv = new HashMap<String, Integer>();
		mapaProv.put("AZUAY", 1);
		mapaProv.put("BOLIVAR", 2);
		mapaProv.put("CAÑAR", 3);
		mapaProv.put("CARCHI", 4);
		mapaProv.put("COTOPAXI", 5);
		mapaProv.put("CHIMBORAZO", 6);
		mapaProv.put("EL ORO", 7);
		mapaProv.put("ESMERALDAS", 8);
		mapaProv.put("GUAYAS", 9);
		mapaProv.put("IMBABURA", 10);
		mapaProv.put("LOJA", 11);
		mapaProv.put("LOS RIOS", 12);
		mapaProv.put("MANABI", 13);
		mapaProv.put("MORONA SANTIAGO", 14);
		mapaProv.put("NAPO", 15);
		mapaProv.put("PASTAZA", 16);
		mapaProv.put("PICHINCHA", 17);
		mapaProv.put("TUNGURAHUA", 18);
		mapaProv.put("ZAMORA CHINCHIPE", 19);
		mapaProv.put("GALAPAGOS", 20);
		mapaProv.put("SUCUMBIOS", 21);
		mapaProv.put("ORELLANA", 22);
		mapaProv.put("STO DGO TSACHILAS", 23);
		mapaProv.put("SANTA ELENA", 24);
		
		mapaProv.put("EUROPA ASIA Y OCEANIA", 26);
		mapaProv.put("EE.UU Y CANADA", 27);
		mapaProv.put("AMERICA LATINA Y EL CARIBE", 28);
		return mapaProv.get(provincia.toUpperCase());
	}
	
	public static Integer cantonChange(String canton) {
		Map<String, Integer> mapaProv = new HashMap<String, Integer>();
		mapaProv.put("CUENCA", 260);
		mapaProv.put("GUALACEO", 265);
		mapaProv.put("GIRON", 270);
		mapaProv.put("PAUTE", 275);
		mapaProv.put("SIGSIG", 280);
		mapaProv.put("SANTA ISABEL", 285);
		mapaProv.put("PUCARA", 555);
		mapaProv.put("CAMILO PONCE ENRIQUEZ", 556);
		mapaProv.put("OÑA", 780);
		mapaProv.put("SAN FERNANDO", 855);
		mapaProv.put("NABON", 885);
		mapaProv.put("CHORDELEG", 915);
		mapaProv.put("SEVILLA DE ORO", 955);
		mapaProv.put("EL PAN", 960);
		mapaProv.put("GUACHAPALA", 990);
		mapaProv.put("GUARANDA", 165);
		mapaProv.put("CHIMBO", 170);
		mapaProv.put("SAN MIGUEL", 175);
		mapaProv.put("CHILLANES", 180);
		mapaProv.put("ECHEANDIA", 185);
		mapaProv.put("CALUMA", 760);
		mapaProv.put("LAS NAVES", 950);
		mapaProv.put("AZOGUES", 235);
		mapaProv.put("CAÑAR", 240);
		mapaProv.put("SUSCAL", 241);
		mapaProv.put("BIBLIAN", 245);
		mapaProv.put("LA TRONCAL", 250);
		mapaProv.put("EL TAMBO", 765);
		mapaProv.put("DELEG", 905);
		mapaProv.put("TULCAN", 5);
		mapaProv.put("MONTUFAR", 10);
		mapaProv.put("ESPEJO", 15);
		mapaProv.put("MIRA", 20);
		mapaProv.put("BOLIVAR", 25);
		mapaProv.put("SAN PEDRO DE HUACA", 995);
		mapaProv.put("LATACUNGA", 100);
		mapaProv.put("PUJILI", 105);
		mapaProv.put("SALCEDO", 110);
		mapaProv.put("SAQUISILI", 115);
		mapaProv.put("PANGUA", 120);
		mapaProv.put("LA MANA", 825);
		mapaProv.put("SIGCHOS", 930);
		mapaProv.put("CHAMBO", 190);
		mapaProv.put("RIOBAMBA", 195);
		mapaProv.put("GUANO", 200);
		mapaProv.put("COLTA", 205);
		mapaProv.put("GUAMOTE", 210);
		mapaProv.put("ALAUSI", 215);
		mapaProv.put("CHUNCHI", 220);
		mapaProv.put("PENIPE", 225);
		mapaProv.put("PALLATANGA", 830);
		mapaProv.put("CUMANDA", 900);
		mapaProv.put("MACHALA", 350);
		mapaProv.put("SANTA ROSA", 355);
		mapaProv.put("ZARUMA", 360);
		mapaProv.put("PASAJE", 365);
		mapaProv.put("PIÑAS", 370);
		mapaProv.put("ARENILLAS", 375);
		mapaProv.put("EL GUABO", 380);
		mapaProv.put("CHILLA", 585);
		mapaProv.put("PORTOVELO", 690);
		mapaProv.put("HUAQUILLAS", 695);
		mapaProv.put("ATAHUALPA", 705);
		mapaProv.put("LAS LAJAS", 755);
		mapaProv.put("MARCABELI", 860);
		mapaProv.put("BALSAS", 875);
		mapaProv.put("ESMERALDAS", 560);
		mapaProv.put("RIO VERDE", 561);
		mapaProv.put("ELOY ALFARO", 565);
		mapaProv.put("MUISNE", 570);
		mapaProv.put("QUININDE", 575);
		mapaProv.put("SAN LORENZO", 580);
		mapaProv.put("ATACAMES", 785);
		mapaProv.put("BALAO", 95);
		mapaProv.put("COLIMES", 125);
		mapaProv.put("EL EMPALME", 385);
		mapaProv.put("GUAYAQUIL", 390);
		mapaProv.put("YAGUACHI", 395);
		mapaProv.put("DAULE", 400);
		mapaProv.put("BALZAR", 415);
		mapaProv.put("MILAGRO", 420);
		mapaProv.put("SAMBORONDON", 425);
		mapaProv.put("SALITRE", 430);
		mapaProv.put("NARANJAL", 435);
		mapaProv.put("EL TRIUNFO", 505);
		mapaProv.put("NARANJITO", 510);
		mapaProv.put("PALESTINA", 675);
		mapaProv.put("PEDRO CARBO", 715);
		mapaProv.put("PLAYAS", 735);
		mapaProv.put("SIMON BOLIVAR", 790);
		mapaProv.put("DURAN", 820);
		mapaProv.put("A.BAQUERIZO MORENO", 835);
		mapaProv.put("SANTA LUCIA", 870);
		mapaProv.put("CRNL MARCELINO MARIDUENAS", 890);
		mapaProv.put("LOMAS DE SARGENTILLO", 920);
		mapaProv.put("NOBOL / PIEDRAHITA", 940);
		mapaProv.put("GRAL. A. ELIZALDE", 985);
		mapaProv.put("ISIDRO AYORA", 986);
		mapaProv.put("IBARRA", 30);
		mapaProv.put("OTAVALO", 35);
		mapaProv.put("COTACACHI", 40);
		mapaProv.put("ANTONIO ANTE", 45);
		mapaProv.put("PIMAMPIRO", 50);
		mapaProv.put("URCUQUI", 55);
		mapaProv.put("CATAMAYO", 290);
		mapaProv.put("ZAPOTILLO", 295);
		mapaProv.put("LOJA", 300);
		mapaProv.put("SARAGURO", 305);
		mapaProv.put("PALTAS", 310);
		mapaProv.put("OLMEDO", 311);
		mapaProv.put("CELICA", 315);
		mapaProv.put("CALVAS", 320);
		mapaProv.put("MACARA", 325);
		mapaProv.put("PUYANGO", 330);
		mapaProv.put("GONZANAMA", 335);
		mapaProv.put("ESPINDOLA", 340);
		mapaProv.put("SOZORANGA", 345);
		mapaProv.put("PINDAL", 730);
		mapaProv.put("QUILANGA", 740);
		mapaProv.put("CHAGUARPAMBA", 815);
		mapaProv.put("BABAHOYO", 515);
		mapaProv.put("VALENCIA", 516);
		mapaProv.put("BABA", 520);
		mapaProv.put("VINCES", 525);
		mapaProv.put("PUEBLO VIEJO", 530);
		mapaProv.put("URDANETA", 535);
		mapaProv.put("QUEVEDO", 540);
		mapaProv.put("VENTANAS", 545);
		mapaProv.put("QUINSALOMA", 546);
		mapaProv.put("MONTALVO", 710);
		mapaProv.put("PALENQUE", 750);
		mapaProv.put("BUENA FE", 945);
		mapaProv.put("MOCACHE", 946);
		mapaProv.put("FLAVIO ALFARO", 230);
		mapaProv.put("PORTOVIEJO", 440);
		mapaProv.put("MONTECRISTI", 445);
		mapaProv.put("JARAMIJO", 446);
		mapaProv.put("MANTA", 450);
		mapaProv.put("JIPIJAPA", 455);
		mapaProv.put("24 DE MAYO", 460);
		mapaProv.put("ROCAFUERTE", 465);
		mapaProv.put("SANTA ANA", 470);
		mapaProv.put("SUCRE", 475);
		mapaProv.put("JAMA", 476);
		mapaProv.put("SAN VICENTE", 477);
		mapaProv.put("CHONE", 480);
		mapaProv.put("BOLIVAR", 485);
		mapaProv.put("JUNIN", 490);
		mapaProv.put("PAJAN", 495);
		mapaProv.put("EL CARMEN", 500);
		mapaProv.put("TOSAGUA", 550);
		mapaProv.put("PICHINCHA", 840);
		mapaProv.put("PEDERNALES", 910);
		mapaProv.put("OLMEDO", 970);
		mapaProv.put("PUERTO LOPEZ", 975);
		mapaProv.put("MORONA", 590);
		mapaProv.put("GUALAQUIZA", 595);
		mapaProv.put("LIMON INDANZA", 600);
		mapaProv.put("SANTIAGO", 605);
		mapaProv.put("SUCUA", 610);
		mapaProv.put("LOGROÑO", 611);
		mapaProv.put("PALORA", 615);
		mapaProv.put("HUAMBOYA", 795);
		mapaProv.put("PABLO SEXTO", 796);
		mapaProv.put("TIWINTZA", 797);
		mapaProv.put("SAN JUAN BOSCO", 925);
		mapaProv.put("TAISHA", 926);
		mapaProv.put("EL CHACO", 255);
		mapaProv.put("TENA", 620);
		mapaProv.put("C. J. AROSEMENA TOLA", 621);
		mapaProv.put("QUIJOS", 635);
		mapaProv.put("ARCHIDONA", 700);
		mapaProv.put("PASTAZA", 680);
		mapaProv.put("MERA", 685);
		mapaProv.put("SANTA CLARA", 880);
		mapaProv.put("ARAJUNO", 881);
		mapaProv.put("QUITO", 60);
		mapaProv.put("CAYAMBE", 65);
		mapaProv.put("MEJIA", 70);
		mapaProv.put("PEDRO MONCAYO", 75);
		mapaProv.put("RUMIÑAHUI", 80);
		mapaProv.put("SAN MIGUEL DE LOS BANCOS", 770);
		mapaProv.put("PEDRO VICENTE MALDONADO", 895);
		mapaProv.put("PUERTO QUITO", 896);
		mapaProv.put("TISALEO", 90);
		mapaProv.put("AMBATO", 135);
		mapaProv.put("PELILEO", 140);
		mapaProv.put("PILLARO", 145);
		mapaProv.put("BAÑOS", 150);
		mapaProv.put("PATATE", 155);
		mapaProv.put("QUERO", 160);
		mapaProv.put("CEVALLOS", 845);
		mapaProv.put("MOCHA", 850);
		mapaProv.put("NANGARITZA", 130);
		mapaProv.put("ZAMORA", 655);
		mapaProv.put("CHINCHIPE", 660);
		mapaProv.put("PALANDA", 661);
		mapaProv.put("YACUAMBI", 665);
		mapaProv.put("YANZATZA", 670);
		mapaProv.put("EL PANGUI", 775);
		mapaProv.put("CENTINELA DEL CONDOR", 980);
		mapaProv.put("PAQUISHA", 981);
		mapaProv.put("SAN CRISTOBAL", 800);
		mapaProv.put("SANTA CRUZ", 805);
		mapaProv.put("ISABELA", 810);
		mapaProv.put("LAGO AGRIO", 625);
		mapaProv.put("CUYABENO", 626);
		mapaProv.put("SUCUMBIOS", 640);
		mapaProv.put("PUTUMAYO", 650);
		mapaProv.put("SHUSHUFINDI", 720);
		mapaProv.put("CASCALES", 745);
		mapaProv.put("GONZALO PIZARRO", 865);
		mapaProv.put("AGUARICO", 630);
		mapaProv.put("FCO.DE ORELLANA", 645);
		mapaProv.put("JOYA DE LOS SACHAS", 725);
		mapaProv.put("LORETO", 935);
		mapaProv.put("SANTO DOMINGO", 85);
		mapaProv.put("LA CONCORDIA", 982);
		mapaProv.put("SALINAS", 405);
		mapaProv.put("SANTA ELENA", 410);
		mapaProv.put("LA LIBERTAD", 965);
		mapaProv.put("ALEMANIA", 11);
		mapaProv.put("AUSTRALIA", 31);
		mapaProv.put("AUSTRIA", 41);
		mapaProv.put("BELGICA", 51);
		mapaProv.put("COREA (SUR) REPUBLICA DE", 101);
		mapaProv.put("CHINA", 141);
		mapaProv.put("ESPAÑA", 171);
		mapaProv.put("FRANCIA", 191);
		mapaProv.put("REINO UNIDO DE GRAN BRETAÑA E IRLANDA DEL NORTE", 201);
		mapaProv.put("HUNGRIA", 231);
		mapaProv.put("ISRAEL", 251);
		mapaProv.put("ITALIA", 261);
		mapaProv.put("JAPON", 271);
		mapaProv.put("PAISES BAJOS (HOLANDA)", 301);
		mapaProv.put("SUECIA", 361);
		mapaProv.put("SUIZA", 371);
		mapaProv.put("FEDERACION DE RUSIA", 381);
		mapaProv.put("INDONESIA", 411);
		mapaProv.put("TURQUIA", 451);
		mapaProv.put("CANADA", 81);
		mapaProv.put("ESTADOS UNIDOS DE AMERICA", 181);
		mapaProv.put("ARGENTINA", 21);
		mapaProv.put("BOLIVIA", 61);
		mapaProv.put("BRASIL", 71);
		mapaProv.put("COLOMBIA", 91);
		mapaProv.put("COSTA RICA", 111);
		mapaProv.put("CUBA", 121);
		mapaProv.put("CHILE", 131);
		mapaProv.put("EL SALVADOR", 161);
		mapaProv.put("GUATEMALA", 211);
		mapaProv.put("HONDURAS", 221);
		mapaProv.put("MEXICO", 281);
		mapaProv.put("PANAMA", 312);
		mapaProv.put("PARAGUAY", 321);
		mapaProv.put("PERU", 331);
		mapaProv.put("EGIPTO", 341);
		mapaProv.put("REPUBLICA DOMINICANA", 351);
		mapaProv.put("URUGUAY", 391);
		mapaProv.put("VENEZUELA", 401);
		mapaProv.put("SUDAFRICA", 441);
		return mapaProv.get(canton.toUpperCase());
	}
}
